// Traces a crop of a public-domain engraving into ink paths for <SketchSVG> (D28, docs/08-assets.md).
//   node scripts/trace-sketch.mjs <source.jpg> <name> --crop w:h:x:y [--blur 1.2] [--threshold 110]
//     [--turd 60] [--width 720] [--tolerance 0.4] [--edges] [--preview out.svg]
// Writes src/content/sketches/<name>.ts ({ viewBox, paths }). The source image is never committed;
// log its origin in docs/08-assets.md. ffmpeg does the image work; potrace (dev only) traces.

import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import potrace from "potrace";

const [source, name, ...rest] = process.argv.slice(2);
if (!source || !name) {
  console.error(
    "usage: node scripts/trace-sketch.mjs <source> <name> --crop w:h:x:y [options]",
  );
  process.exit(1);
}
const opt = (flag, fallback) => {
  const i = rest.indexOf(flag);
  return i === -1 ? fallback : rest[i + 1];
};
const crop = opt("--crop", null);
const blur = Number(opt("--blur", "1.2"));
const threshold = Number(opt("--threshold", "110"));
const turd = Number(opt("--turd", "60"));
const width = Number(opt("--width", "720"));
const edges = rest.includes("--edges"); // contour drawing instead of ink masses
const tolerance = Number(opt("--tolerance", "0.4"));
const preview = opt("--preview", null); // optional: also write the raw traced SVG here

// 1. crop, grayscale, soften the hatching, scale, threshold to pure ink
const dir = mkdtempSync(path.join(tmpdir(), "sketch-"));
const bitmap = path.join(dir, "ink.png");
const filters = [
  crop && `crop=${crop}`,
  "format=gray",
  `scale=${width}:-1:flags=lanczos`,
  blur > 0 && `gblur=sigma=${blur}`,
  // edges: bright contour lines on black, inverted to dark lines on white
  edges && "edgedetect=low=0.08:high=0.22,negate",
  `lut=y='if(lt(val,${threshold}),0,255)'`,
]
  .filter(Boolean)
  .join(",");
execFileSync("ffmpeg", [
  "-hide_banner",
  "-loglevel",
  "error",
  "-y",
  "-i",
  source,
  "-vf",
  filters,
  bitmap,
]);

// 2. trace the black ink to smooth paths
const svg = await new Promise((resolve, reject) =>
  potrace.trace(
    bitmap,
    {
      turdSize: turd,
      optTolerance: tolerance,
      alphaMax: 1,
      threshold: 128,
      color: "#000",
    },
    (err, out) => (err ? reject(err) : resolve(out)),
  ),
);
rmSync(dir, { recursive: true, force: true });
if (preview) writeFileSync(preview, svg);

const viewBox =
  svg.match(/viewBox="([^"]+)"/)?.[1] ??
  svg
    .match(/width="(\d+)" height="(\d+)"/)
    .slice(1)
    .join(" ");
const vb = viewBox.split(" ").length === 2 ? `0 0 ${viewBox}` : viewBox;
// one decimal is invisible at sketch scale and cuts the path data by about a third
const d = svg
  .match(/ d="([^"]+)"/)[1]
  .replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));
// potrace emits one compound path; split it into separate subpaths so each can draw on in turn
const paths = d
  .split(/(?=M)/)
  .map((p) => p.trim().replace(/\s+/g, " "))
  .filter(Boolean);

mkdirSync("src/content/sketches", { recursive: true });
const out = path.join("src/content/sketches", `${name}.ts`);
writeFileSync(
  out,
  `// Generated by scripts/trace-sketch.mjs. Do not edit by hand; see docs/08-assets.md for the source.\n` +
    `import type { Sketch } from "./types";\n\n` +
    `export const ${name.replace(/-(\w)/g, (_, c) => c.toUpperCase())}: Sketch = {\n` +
    `  viewBox: "${vb}",\n  paths: ${JSON.stringify(paths)},\n};\n`,
);
console.log(
  `wrote ${out}: ${paths.length} paths, ${(d.length / 1024).toFixed(1)} KB of path data`,
);
